name: glasso
description: Glasso - 精美的壁纸与语录应用
publish_to: none
version: 1.0.0+1
environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8 # 图标
  get: ^4.7.2 # 状态管理 + 路由
  liquid_glass_renderer: 0.2.0-dev.3 # 液体玻璃效果
  get_storage: ^2.1.1 # 本地存储
  permission_handler: ^12.0.1 # 权限管理
  gal: ^2.3.2 # 保存到相册
  heroine: ^0.5.0+2 # 英雄动画升级版
  smooth_sheets: ^0.15.0 # 平滑弹窗
  motor: ^1.0.1 # 动画
  stupid_simple_sheet: ^0.5.0 # 简单弹窗
  animated_text_kit: ^4.3.0 # 动画文本
  flutter_animate: ^4.5.2 # 动画
  animate_do: ^4.2.0 # 预设动画
  lottie: ^3.3.2 # Lottie 动画
  logger: ^2.6.2 # 日志
  flutter_staggered_grid_view: ^0.7.0 # 瀑布流
  extended_image: ^10.0.1 # 支持图片/GIF 和手势
  video_player: ^2.9.2 # 视频播放支持
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    # 图片资源
    - assets/images/
    - assets/images/wallpapers/abstract/
    - assets/images/wallpapers/aesthetic/
    - assets/images/wallpapers/gradient/
    - assets/images/wallpapers/minimal/
    - assets/images/avatars/anime/
    - assets/images/avatars/cute/
    - assets/images/avatars/minimal/
    - assets/images/avatars/vintage/
    - assets/images/avatars/
    - assets/images/others/
    
    # 视频资源
    - assets/videos/liquid/
    - assets/videos/liquid/thumbnails/
    - assets/videos/colorful/
    - assets/videos/colorful/thumbnails/
