name: glasso
description: Glasso - 精美的壁纸与语录应用
publish_to: none
version: 1.0.0+1
environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  liquid_glass_renderer: ^0.1.1-dev.25
  get_storage: ^2.1.1
  permission_handler: ^12.0.1
  gal: ^2.3.2
  heroine: ^0.5.0+2
  smooth_sheets: ^0.15.0
  motor: ^1.0.1
  stupid_simple_sheet: ^0.5.0
  animated_text_kit: ^4.3.0
  flutter_animate: ^4.5.2
  animate_do: ^4.2.0
  lottie: ^3.3.2
  logger: ^2.6.2
  flutter_staggered_grid_view: ^0.7.0
  photo_view: ^0.15.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/images/avatars/anime/
  - assets/images/avatars/cute/
  - assets/images/avatars/minimal/
  - assets/images/avatars/vintage/
  - assets/images/wallpapers/abstract/
  - assets/images/wallpapers/aesthetic/
  - assets/images/wallpapers/gradient/
  - assets/images/wallpapers/minimal/
  - assets/lottie/
